blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/akaanakbaik/libsignal#readme
    about: Check the documentation first
  - name: Security Issue
    url: https://github.com/akaanakbaik/libsignal/security/policy
    about: Please report security vulnerabilities here
