name: Manual Release
on:
  workflow_dispatch:
    inputs:
      increment:
        type: string
        description: 'Must be: patch, minor, major, pre* or <version>'
        required: true
        default: 'patch'
permissions:
  contents: write
jobs:
  manual-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: npm
          registry-url: https://registry.npmjs.org
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: Release
        run: npx --yes release-it --increment ${{ inputs.increment }}
